WITH PARENT_TABLE AS (
    SELECT ITEM_ID
    FROM ITEM_TREE
    WHERE PARENT_ITEM_ID IS NULL
    )

SELECT I.ITEM_ID, I.ITEM_NAME
FROM ITEM_INFO I
JOIN PARENT_TABLE T ON I.ITEM_ID = T.ITEM_ID
ORDER BY ITEM_ID;