WITH AVAILABLE_CARS AS (
    SELECT CAR_ID, CAR_TYPE, DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE IN ('세단', 'SUV')
    AND CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE NOT (
            END_DATE < '2022-11-01' OR START_DATE > '2022-11-30'
        )
    )
),
DISCOUNT AS (
    SELECT CAR_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE = '30일 이상'
),
FEE_CALCULATED AS (
    SELECT 
        A.CAR_ID,
        A.CAR_TYPE,
        FLOOR(A.DAILY_FEE * 30 * (1 - D.DISCOUNT_RATE / 100.0)) AS FEE
    FROM AVAILABLE_CARS A
    JOIN DISCOUNT D ON A.CAR_TYPE = D.CAR_TYPE
)
SELECT CAR_ID, CAR_TYPE, FEE
FROM FEE_CALCULATED
WHERE FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;
