# 2022-10-16에 대여중인 차 목록 만들기
WITH RENTING AS (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE
)

SELECT H.CAR_ID, 
    CASE
        WHEN R.CAR_ID IS NOT NULL THEN '대여중'
        ELSE '대여 가능'
    END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
LEFT JOIN RENTING R ON H.CAR_ID = R.CAR_ID
GROUP BY H.CAR_ID 
ORDER BY H.CAR_ID DESC;