SELECT A.FLAVOR
FROM FIRST_HALF B
INNER JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_TOTAL_ORDER
           FROM JULY GROUP BY FLAVOR) A
ON B.FLAVOR = A.FLAVOR
ORDER BY TOTAL_ORDER + JULY_TOTAL_ORDER DESC
LIMIT 3
