WITH MAX_FISH_TYPE AS(
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO I 
    GROUP BY FISH_TYPE
    )

SELECT I.ID, N.FISH_NAME, I.LENGTH
FROM FISH_INFO I
JOIN FISH_NAME_INFO N 
    ON N.FISH_TYPE = I.FISH_TYPE
JOIN MAX_FISH_TYPE M 
    ON M.FISH_TYPE = I.FISH_TYPE AND I.LENGTH = M.MAX_LENGTH
