-- 2022년도 한해 평가 점수가 가장 높은 사원 
-- 점수(상+하, SCORE), 사번, 성명, 직책, 이메일 

WITH SCORE_TABLE AS (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
    ORDER BY SUM(SCORE) DESC
    LIMIT 1)

SELECT S.SCORE, S.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES E
JOIN SCORE_TABLE S ON E.EMP_NO = S.EMP_NO;